import { Appointment, Doctor } from "../types";

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Maya Patel",
    specialty: "Family medicine",
    experience: "12 years experience",
    rating: 4.9,
    nextAvailable: "Today, 4:30 PM",
    initials: "MP",
    tone: "coral",
  },
  {
    id: 2,
    name: "Dr. James Wilson",
    specialty: "Cardiology",
    experience: "15 years experience",
    rating: 4.8,
    nextAvailable: "Tomorrow, 9:00 AM",
    initials: "JW",
    tone: "blue",
  },
  {
    id: 3,
    name: "Dr. Sofia Martinez",
    specialty: "Dermatology",
    experience: "9 years experience",
    rating: 4.9,
    nextAvailable: "Wed, 11:15 AM",
    initials: "SM",
    tone: "mint",
  },
];

export const patientAppointments: Appointment[] = [
  {
    id: 1,
    doctor: "Dr. Maya Patel",
    specialty: "Family medicine",
    date: "Tue, Aug 27",
    time: "4:30 PM",
    status: "Confirmed",
    mode: "Video consultation",
    initials: "MP",
    tone: "coral",
  },
  {
    id: 2,
    doctor: "Dr. Sofia Martinez",
    specialty: "Dermatology",
    date: "Fri, Aug 30",
    time: "11:15 AM",
    status: "Pending",
    mode: "Video consultation",
    initials: "SM",
    tone: "mint",
  },
  {
    id: 3,
    doctor: "Dr. James Wilson",
    specialty: "Cardiology",
    date: "Mon, Sep 02",
    time: "9:00 AM",
    status: "Confirmed",
    mode: "In clinic",
    initials: "JW",
    tone: "blue",
  },
];

export const doctorAppointments: Appointment[] = [
  {
    id: 11,
    doctor: "Dr. Maya Patel",
    patient: "Alex Johnson",
    specialty: "Follow-up consultation",
    date: "Today",
    time: "4:30 PM",
    status: "Confirmed",
    mode: "Video consultation",
    initials: "AJ",
    tone: "coral",
  },
  {
    id: 12,
    doctor: "Dr. Maya Patel",
    patient: "Nina Roberts",
    specialty: "Annual wellness review",
    date: "Today",
    time: "5:15 PM",
    status: "Confirmed",
    mode: "Video consultation",
    initials: "NR",
    tone: "mint",
  },
  {
    id: 13,
    doctor: "Dr. Maya Patel",
    patient: "Liam Chen",
    specialty: "Medication review",
    date: "Tomorrow",
    time: "9:00 AM",
    status: "Pending",
    mode: "In clinic",
    initials: "LC",
    tone: "blue",
  },
];
